services:
  nginx:
    image: nginx:1.23.1
    volumes:
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./backend:/var/www/backend
      - ./_docker/nginx/logs:/var/log/nginx
    ports:
      - "8876:80"
    container_name: project_nginx
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./_docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www/backend
    ports:
      - "8080:80"
    environment:
      - API_PORT=8080
    depends_on:
      - postgres
    container_name: project_backend
  #  frontend:
  #    build: ./_docker/frontend
  #    context: ./_docker/frontend
  #    volumes:
  #      - ./frontend:/var/www/frontend
  #    ports:
  #      - "8081:80"
  #    depends_on:
  #      - backend
  #    networks:
  #      - app-net
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: khtrand
      POSTGRES_PASSWORD: qurboni
      POSTGRES_DB: test_docker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: project_postgres
volumes:
  postgres_data:
